sudo: required
services: 
        - docker

before_install:
        - docker build -t aashkulkarni/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true aashkulkarni/docker-react npm run test -- --coverage
